### ISSUE TITLE
Suggestion: Try to avoid too much whitespace in the code.

### ISSUE THREAD

**Issue by josephtkim** [Kasiopeia/prj-rev-bwfs-dasmoto#5]
In the CSS code, there is a lot of empty space, also known and white space, in between sections of code. It is best to use them efficiently, and not too liberally since it can make the file longer than necessary. It is usually best to leave one or a few empty lines in between each selector; try to stay consistent with the amount. 

Here is how it might look
```css
body {
    font-family: Helvetica, sans-serif;
    margin: 8px;
}

/*header*/
.header {
    background-image: url(https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg);
}

h1 {
    color: khaki;
    font-size: 100px;
    text-align: center;
    font-weight: bold;
}

h2 {
    font-size: 32px;
    font-weight: bold;
    color: #fff;
}

/*brushes*/
.brushes h2 {
    background-color: mediumspringgreen;
}

.price {
    color: blue;
    font-weight: bold;
}

/*frames*/
.frames h2 {
    background-color: lightcoral;
}

/*paint*/
.paint h2 {
    background-color: skyblue;
}
```
